[workspace]
members = [
    "programs/programs/amm",
    "hook/programs/hook"
]

[provider]
cluster = "devnet"
wallet = "C:/Users/gajer/.config/solana/id.json"

[programs.devnet]
amm = "5oMNX1WenL9DKfb5Yyf28c7Tbns2nqmMnv1FoTMJwuju"
hook = "FYUyJbrXRQJpGnjfZTFCdEUvFnknkTGbrdHhRUQkezib"

[programs.localnet]
amm = "5oMNX1WenL9DKfb5Yyf28c7Tbns2nqmMnv1FoTMJwuju"
hook = "FYUyJbrXRQJpGnjfZTFCdEUvFnknkTGbrdHhRUQkezib"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[features]
seeds = false
skip-lint = false
