[workspace]
members = [
    "programs/programs/amm",
    "hook/programs/hook"
]

[provider]
cluster = "devnet"
wallet = "C:/Users/gajer/.config/solana/id.json"

[programs.devnet]
amm = "3KeeJh4v2qeSPMWekPwskMPkYVVBhqinixmEnWVdZ9mU"
hook = "9JJWgpjTmmXYNhsUgqanojpfGdL5ovQTPaF53Gb8qX4J"

[programs.localnet]
amm = "3KeeJh4v2qeSPMWekPwskMPkYVVBhqinixmEnWVdZ9mU"
hook = "9JJWgpjTmmXYNhsUgqanojpfGdL5ovQTPaF53Gb8qX4J"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[features]
seeds = false
skip-lint = false

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
debug = false
