[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hook = "FeawNjHM6jkRSYfkyhHn7Z91cGt59V7yFstTKHw8ckpe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\gajer\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
