[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "64wzpszxV5JiGduwzJJSPDAKYWWJER2Z9xmE7Yr7Xzx1"

[programs.devnet]
amm = "64wzpszxV5JiGduwzJJSPDAKYWWJER2Z9xmE7Yr7Xzx1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = 'C:\Users\gajer\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
